// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/roots-salon/CinematicHome.tsx": () => import("../components/mockups/roots-salon/CinematicHome.tsx")
};
